// Recurrence series split — "this and future" (§57).
// ───────────────────────────────────────────────────────────
// Splits a recurring series at a given occurrence: the OLD series becomes
// historical (effective_until caps it before the split occurrence), and a
// NEW series is created for the split occurrence and all future occurrences.
//
// Historical recurrence integrity (§57):
//   - Past occurrences remain on the old series (effective_until caps them).
//   - Past exceptions (original_start_time < split) stay on the old series.
//   - Future exceptions (original_start_time >= split) migrate to the new
//     series, re-keyed with the new series ID. If the new series generates
//     occurrences at the same original start times, the exceptions apply
//     correctly; otherwise they are harmless orphans (no incorrect behaviour).
//   - The old series gets superseded_by_id → new series (audit link).
//
// Idempotency: calendarEventIdempotency key split__ownerType__ownerId__split:oldEventId:splitStart.
// A repeated call returns the existing new series ID without creating a duplicate.
//
// Booking-owned series cannot be split here (source_system 'booking' —
// booking events are non-recurring; if a series is booking-owned, reject).

import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { db, allowedOrigins, getIdentityId, hasBusinessCalendarPermission } from './shared';
import { idempotencyDocId, maintainProjection } from './calendarEvent';
import { appendScheduleHistory } from './calendarEventHistory';
import { setOccurrenceException, listExceptions, exceptionDocId } from './calendarEventExceptions';
import { moderateEventContent } from './contentModeration';

const EVENTS = 'calendarEvents';
const EXCEPTIONS = 'calendarEventExceptions';
const IDEMPOTENCY = 'calendarEventIdempotency';

// ── splitRecurrenceSeries ───────────────────────────────────
// Request: {
//   series_event_id, split_start_time,
//   new_start_time?, new_end_time?, new_recurrence_rule?,
//   new_title?, new_description?
// }
// Returns: { old_event_id, new_event_id, effective_until, created }
export const splitRecurrenceSeries = onCall(
  { region: 'europe-west2', cors: allowedOrigins },
  async (request) => {
    if (!request.auth) {
      throw new HttpsError('unauthenticated', 'Authentication required');
    }
    const callerIdentityId = await getIdentityId(request.auth.uid);
    const nowIso = new Date().toISOString();
    const {
      series_event_id, split_start_time,
      new_start_time, new_end_time, new_recurrence_rule,
      new_title, new_description,
    } = request.data || {};

    // ── Validate required fields ──
    if (!series_event_id || !split_start_time) {
      throw new HttpsError('invalid-argument', 'series_event_id and split_start_time are required');
    }

    // ── Content moderation (if new title/description provided) ──
    const moderation = moderateEventContent(
      new_title !== undefined ? new_title : null,
      new_description !== undefined ? new_description : null,
    );
    if (!moderation.passed) {
      throw new HttpsError('failed-precondition', moderation.reason || 'Content moderation failed');
    }

    // ── Load old series ──
    const oldDoc = await db.collection(EVENTS).doc(series_event_id).get();
    if (!oldDoc.exists) {
      throw new HttpsError('not-found', 'Series event not found');
    }
    const oldEvent = oldDoc.data()!;

    // ── Permission (same as occurrence exception) ──
    const isCreator = oldEvent.created_by_id === callerIdentityId;
    const isOwner = oldEvent.owner_type === 'identity' && oldEvent.owner_id === callerIdentityId;
    let isBizManager = false;
    if (oldEvent.owner_type === 'business' && oldEvent.business_id) {
      isBizManager = await hasBusinessCalendarPermission(oldEvent.business_id, callerIdentityId);
    }
    if (!isCreator && !isOwner && !isBizManager) {
      throw new HttpsError('permission-denied', 'Not authorised to modify this series');
    }

    // ── Must be recurring ──
    if (!oldEvent.recurrence_rule) {
      throw new HttpsError('failed-precondition', 'Event is not recurring');
    }

    // ── Booking-owned series cannot be split here ──
    if (oldEvent.source_system === 'booking') {
      throw new HttpsError('failed-precondition', 'Booking-owned events cannot be split via Calendar');
    }

    // ── Already superseded? Reject (don't split a historical series) ──
    if (oldEvent.superseded_by_id) {
      throw new HttpsError('failed-precondition', 'Series has already been superseded');
    }

    // ── Compute effective_until for old series ──
    // Just before the split occurrence so the split occurrence and later
    // are NOT generated by the old series (occStart <= effectiveUntil).
    const splitDate = new Date(split_start_time);
    const effectiveUntilIso = new Date(splitDate.getTime() - 1).toISOString();

    // ── New series properties ──
    const newStart = new_start_time || split_start_time;
    let newEndValue = new_end_time;
    if (!newEndValue) {
      const oldDuration = new Date(oldEvent.end_time).getTime() - new Date(oldEvent.start_time).getTime();
      newEndValue = new Date(new Date(newStart).getTime() + oldDuration).toISOString();
    }
    const newRrule = new_recurrence_rule || oldEvent.recurrence_rule;

    // ── Idempotency ──
    const splitSourceId = `${series_event_id}:${split_start_time}`;
    const idempKey = idempotencyDocId(oldEvent.owner_type, oldEvent.owner_id || '', 'split', splitSourceId);
    const idempRef = db.collection(IDEMPOTENCY).doc(idempKey);

    let newEventId = '';
    let existingNewId: string | null = null;

    await db.runTransaction(async (tx) => {
      const idempSnap = await tx.get(idempRef);
      if (idempSnap.exists && idempSnap.data()?.event_id) {
        existingNewId = idempSnap.data()!.event_id as string;
        return;
      }

      // Cap the old series — effective_until + superseded_by_id
      tx.update(db.collection(EVENTS).doc(series_event_id), {
        effective_until: effectiveUntilIso,
        superseded_by_id: '', // placeholder — set to newRef.id below in a 2nd update
        _updated_date: nowIso,
      });

      // Create new series
      const newRef = db.collection(EVENTS).doc();
      newEventId = newRef.id;
      const newEventData: Record<string, any> = {
        owner_id: oldEvent.owner_id,
        owner_type: oldEvent.owner_type,
        operating_context: oldEvent.operating_context || 'personal',
        title: new_title || oldEvent.title,
        description: new_description !== undefined ? new_description : oldEvent.description,
        start_time: newStart,
        end_time: newEndValue,
        timezone: oldEvent.timezone || 'UTC',
        all_day: oldEvent.all_day || false,
        location_id: oldEvent.location_id || null,
        location_type: oldEvent.location_type || 'physical',
        meeting_url: oldEvent.meeting_url || null,
        visibility: oldEvent.visibility || 'private',
        lifecycle_state: 'scheduled',
        source_system: oldEvent.source_system || 'manual',
        source_id: `split:${series_event_id}:${split_start_time}`,
        business_id: oldEvent.business_id || null,
        created_by_id: oldEvent.created_by_id, // preserve original creator
        recurrence_rule: newRrule,
        assigned_identity_ids: oldEvent.assigned_identity_ids || [],
        invited_identity_ids: oldEvent.invited_identity_ids || [],
        invited_guest_emails: oldEvent.invited_guest_emails || [],
        _created_date: nowIso,
        _updated_date: nowIso,
      };
      tx.set(newRef, newEventData);

      // Set superseded_by_id on old series → new series
      tx.update(db.collection(EVENTS).doc(series_event_id), {
        superseded_by_id: newRef.id,
      });

      // Idempotency record
      tx.set(idempRef, {
        event_id: newRef.id,
        owner_type: oldEvent.owner_type,
        owner_id: oldEvent.owner_id,
        source_system: 'split',
        source_id: splitSourceId,
        _created_date: nowIso,
        _updated_date: nowIso,
      });
    });

    const finalNewId = existingNewId || newEventId;
    const created = !existingNewId;

    if (created) {
      // ── Migrate future exceptions to the new series ──
      // Exceptions with original_start_time >= split_start_time move to
      // the new series (re-keyed). Past exceptions stay on the old series.
      const exceptions = await listExceptions(series_event_id);
      for (const exc of exceptions) {
        if (new Date(exc.original_start_time).getTime() >= splitDate.getTime()) {
          // Delete from old series
          await db.collection(EXCEPTIONS).doc(exceptionDocId(series_event_id, exc.original_start_time)).delete();
          // Re-create on new series (idempotent — deterministic doc ID)
          await setOccurrenceException(
            finalNewId,
            exc.original_start_time,
            exc.exception_type,
            exc.created_by_id,
            exc.new_start_time,
            exc.new_end_time,
            exc.reason,
          );
        }
      }

      // ── Schedule history ──
      // Old series: recurrence_changed (superseded)
      await appendScheduleHistory({
        event_id: series_event_id,
        change_type: 'recurrence_changed',
        previous_start_time: oldEvent.start_time,
        previous_end_time: oldEvent.end_time,
        new_start_time: effectiveUntilIso,
        new_end_time: null,
        changed_at: nowIso,
        actor_id: callerIdentityId,
        source_system: oldEvent.source_system || 'manual',
      });
      // New series: created
      await appendScheduleHistory({
        event_id: finalNewId,
        change_type: 'created',
        previous_start_time: null,
        previous_end_time: null,
        new_start_time: newStart,
        new_end_time: newEndValue,
        changed_at: nowIso,
        actor_id: callerIdentityId,
        source_system: oldEvent.source_system || 'manual',
      });

      // ── Maintain projections ──
      await maintainProjection(series_event_id, { ...oldEvent, effective_until: effectiveUntilIso, superseded_by_id: finalNewId });
      const newEventData: Record<string, any> = {
        owner_id: oldEvent.owner_id,
        owner_type: oldEvent.owner_type,
        operating_context: oldEvent.operating_context || 'personal',
        title: new_title || oldEvent.title,
        description: new_description !== undefined ? new_description : oldEvent.description,
        start_time: newStart,
        end_time: newEndValue,
        timezone: oldEvent.timezone || 'UTC',
        all_day: oldEvent.all_day || false,
        location_id: oldEvent.location_id || null,
        location_type: oldEvent.location_type || 'physical',
        meeting_url: oldEvent.meeting_url || null,
        visibility: oldEvent.visibility || 'private',
        lifecycle_state: 'scheduled',
        source_system: oldEvent.source_system || 'manual',
        source_id: `split:${series_event_id}:${split_start_time}`,
        business_id: oldEvent.business_id || null,
        created_by_id: oldEvent.created_by_id,
        recurrence_rule: newRrule,
        assigned_identity_ids: oldEvent.assigned_identity_ids || [],
        invited_identity_ids: oldEvent.invited_identity_ids || [],
        invited_guest_emails: oldEvent.invited_guest_emails || [],
      };
      await maintainProjection(finalNewId, newEventData);
    }

    return {
      old_event_id: series_event_id,
      new_event_id: finalNewId,
      effective_until: effectiveUntilIso,
      created,
    };
  },
);